### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by dbof10** [NewtronLabs/IpcEventBus#2]
I'm running on api 27
Stacktrace: 
```
**02-15 09:58:21.901 6248-6248/com.newtronlabs.ipceventbus.app2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.newtronlabs.ipceventbus.app2, PID: 6248
                                                                                java.lang.ExceptionInInitializerError
                                                                                    at com.newtronlabs.ipceventbus.connection.factory.ConnectorFactory.getInstance(Unknown Source)
                                                                                    at com.newtronlabs.ipceventbus.app2.MainActivity.onCreate(MainActivity.java:38)
                                                                                    at android.app.Activity.performCreate(Activity.java:6679)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                 Caused by: java.lang.RuntimeException: Stub!
                                                                                    at com.newtronlabs.ipceventbus.connection.factory.ConnectorFactory.<init>(Unknown Source)
                                                                                    at com.newtronlabs.ipceventbus.connection.factory.ConnectorFactory.<clinit>(Unknown Source)
                                                                                    at com.newtronlabs.ipceventbus.connection.factory.ConnectorFactory.getInstance(Unknown Source) 
                                                                                    at com.newtronlabs.ipceventbus.app2.MainActivity.onCreate(MainActivity.java:38) 
                                                                                    at android.app.Activity.performCreate(Activity.java:6679) 
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                    at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
**
```
If I apply the plugin, I can't compile with error ```Error:Resolving configuration 'androidTestCompile' directly is not allowed```

**Comment by NewtronLabs** [comment]
Hi @dbof10! 

The support for Gradle 3 is still in its alpha stages and undergoing testing. In the meantime you can use the alpha version which should resolve this problem.

```
dependencies {
    classpath 'com.android.tools.build:gradle:3.0.1'
    classpath "com.newtronlabs.android:plugin:2.0.0.alpha"
}
```

The other option is to use Gradle 2. 

Newtron Labs
Solving problems so you don't have to.
IPC EventBus Team

**Comment by dbof10** [comment]
Thanks
